version: "3.0"
services:
  web:
    depends_on:
      - redis
    ports:
      - "6379:6379"
    links:
      - redis:redis

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data:
